Repository Chavin30/back-banco, pull requests merged in 2022-04, with the labels that each got.

#10 [IMP] CRUD_Concept
  controllers/conceptController
  git-readme.md
  middleware/validators/conceptValidator.js
  migrations/20220319200336-create-concept.js
  package-lock.json
  package.json
  routes/conceptRoutes.js
Labels: review needed

#12 [IMP] getclavetoken
  .env-example
  controllers/tokenController.js
  middleware/validators/tokenValidator.js
  models/Client.js
  routes/2-indexRoutes.js
  routes/claveRoutes.js
Labels: review needed

#13 CRUD de executive y validaciones
  controllers/executiveController.js
  middleware/validators/executiveValidator.js
  routes/executiveRoutes.js
Labels: review needed

#17 [IMP] login and middlerware for validate token [FIX-to-development]
  controllers/conceptController.js
  controllers/executiveController.js
  controllers/loginController.js
  middleware/validateToken.js
  middleware/validators/executiveValidator.js
  middleware/validators/loginValidator.js
  migrations/20220318160052-create-position.js
  migrations/20220319204158-denomination_cut.js
  migrations/20220406023324-branch_executive.js
  models/Executive.js
  routes/areaRoutes.js
  routes/claveRoutes.js
  routes/commissionRoutes.js
  routes/conceptRoutes.js
  routes/denominationRoutes.js
  routes/executiveRoutes.js
  routes/loginRoutes.js
  routes/positionRoutes.js
  seeders/20220318165817-Area.js
  seeders/20220318170452-Position.js
  seeders/20220318170711-Branch.js
  seeders/20220319214807-Executive.js
  seeders/global-info/variables.js
Labels: done

#19 [FIX] executive controller, routes, model, and set id_areas visible i…
  controllers/executiveController.js
  middleware/validators/executiveValidator.js
  models/Area.js
  models/Executive.js
  routes/executiveRoutes.js
Labels: done

#24 [IMP] cuts crud -controller,routes and validato,[FIX]migration,model,…
  controllers/cutController.js
  middleware/validators/cutValidator.js
  migrations/20220319200349-create-cut.js
  models/Cut.js
  routes/cutRoutes.js
  seeders/20220319213301-Denomination.js
Labels: review needed

#27 [Fix] crud areas
  controllers/areaController.js
  controllers/loginController.js
  middleware/validators/areaValidator.js
  migrations/20220318160044-create-position.js
  migrations/20220318160045-create-area.js
  migrations/20220318161049-create-executive.js
  models/Area.js
  models/Executive.js
  models/Position.js
  seeders/20220318165816-Position.js
  seeders/20220318165817-Area.js
  seeders/global-info/variables.js
Labels: done

#28 Fix crud executives#26
  controllers/cutController.js
  controllers/executiveController.js
  middleware/validators/executiveValidator.js
  migrations/20220318160045-create-area.js
  seeders/20220319214807-Executive.js
Labels: done

#29 [IMP] crud client done,[FIX] migrations
  .env-example
  controllers/beneficiaryController.js
  controllers/clientController.js
  controllers/tokenController.js
  middleware/validators/clientValidator.js
  migrations/20220319190207-create-account.js
  migrations/20220319190213-create-card.js
  migrations/20220319203507-create-beneficiary.js
  migrations/20220420014717-create-document.js
  models/Beneficiary.js
  models/Client.js
  models/Document.js
  package-lock.json
  routes/clientRoutes.js
  seeders/20220329160259-Client.js
  seeders/20220420024242-Acount.js
  seeders/20220420024243-beneficiaries.js
  seeders/20220420024301-document.js
  seeders/20220420150144-Card.js
Labels: review needed

#35 [IMP] interest and creditdetails
  controllers/creditDetailsController.js
  controllers/interestsController.js
  middleware/validators/creditDetailsValidator.js
  middleware/validators/interestsValidator.js
  routes/creditdetailRoutes.js
  routes/interestRoutes.js
Labels: review needed

#37 [FIX] creditdetails, [IMP] new seeders
  middleware/validators/creditDetailsValidator.js
  migrations/20220422024901-create-creditdetail.js
  models/Creditdetail.js
  routes/creditdetailRoutes.js
  seeders/20220320162208-Cashbox.js
  seeders/20220329160259-Client.js
  seeders/20220420024242-Account.js
  seeders/20220420024243-beneficiaries.js
  seeders/20220423154149-Creditdetails.js
  seeders/20220423154622-Interest.js
  seeders/20220424025206-Concept.js
  seeders/20220424195408-Account_creditdetails.js
  seeders/20220424195701-Mortgage.js
Labels: done

#42 [IMP] security through enviroments variables
  .env-example
  .gitignore
  config/config.js
  models/index.js
  seeders/20220319214807-Executive.js
Labels: assigned

#44 fix_commission#40_pr
  config/config.json
  controllers/commissionController.js
  routes/commissionRoutes.js
Labels: done

#45 Fix transactions
  controllers/transactionController.js
  helpers/mailer.js
  middleware/validators/transactionValidator.js
  routes/transactionRoutes.js
  seeders/20220319214807-Executive.js
  seeders/20220329160259-Client.js
  seeders/20220420024242-Account.js
  seeders/20220420024301-document.js
  seeders/20220420150144-Card.js
  seeders/20220424025206-Concept.js
  seeders/20220424195701-Mortgage.js
  seeders/20220426012129-transaction.js
Labels: done

#48 [IMP] crud client,accounts,cards,mortgages,beneficiares with validations
  controllers/accountController.js
  controllers/beneficiaryController.js
  controllers/cardController.js
  controllers/clientController.js
  controllers/documentController.js
  controllers/guaranteeController.js
  controllers/mortgageController.js
  controllers/propertyController.js
  middleware/validators/accountValidator.js
  middleware/validators/beneficiaryValidator.js
  middleware/validators/cardValidator.js
  middleware/validators/clientValidator.js
  middleware/validators/documentValidator.js
  middleware/validators/guaranteeValidator.js
  middleware/validators/mortgageValidator.js
  middleware/validators/propertyValidator.js
  migrations/20220319190213-create-card.js
  migrations/20220422022037-create-mortgage.js
  models/Account.js
  routes/2-indexRoutes.js
  routes/accountRoutes.js
  routes/beneficiaryRoutes.js
  routes/cardRoutes.js
  routes/clientRoutes.js
  routes/documentRoutes.js
  routes/guaranteeRoutes.js
  routes/mortgageRoutes.js
  routes/propertyRoutes.js
Labels: done

#49 documentation#46
  controllers/areaController.js
  controllers/cashboxController.js
  controllers/commissionController.js
  controllers/conceptController.js
  controllers/creditDetailsController.js
  controllers/denominationController.js
  controllers/executiveController.js
  controllers/interestsController.js
  controllers/loginController.js
  controllers/positionController.js
  controllers/tokenController.js
  controllers/transactionController.js
Labels: done

#51 [IMP] accountStatus and clientInfo
  config/config.json
  controllers/reportController.js
  helpers/pdfmailer.js
  package-lock.json
  package.json
  routes/reportRoutes.js
Labels: done
